# Generated by Django 3.2.9 on 2021-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinelist',
            name='interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('bimonthly', 'Bimonthly')], max_length=12, null=True),
        ),
    ]
