# Generated by Django 3.2.9 on 2021-11-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0002_pipelinelist_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinelist',
            name='output_image',
            field=models.CharField(choices=[('true-colour', 'True Colour Image'), ('false-colour-urban', 'False Colour Urban'), ('false-colour-infrared', 'False Colour Infrared'), ('near-infrared', 'Near Infrared')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='resolution',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
